/* NEGATIVE RUNNER: a small, pooled Three.js runner with intentionally bad scoring. */
class AudioManager {
  constructor(){ this.context=null; this.muted=false; }
  init(){ if(!this.context) this.context=new (window.AudioContext||window.webkitAudioContext)(); if(this.context.state==='suspended') this.context.resume(); }
  tone(frequency=440,duration=.08,type='square'){ if(this.muted)return; this.init(); const osc=this.context.createOscillator(); const gain=this.context.createGain(); osc.type=type; osc.frequency.value=frequency; gain.gain.setValueAtTime(.045,this.context.currentTime); gain.gain.exponentialRampToValueAtTime(.001,this.context.currentTime+duration); osc.connect(gain).connect(this.context.destination); osc.start(); osc.stop(this.context.currentTime+duration); }
  jump(){this.tone(520,.12,'triangle')} collision(){this.tone(90,.3,'sawtooth')} point(){this.tone(250,.035)} gameOver(){this.tone(70,.5,'sawtooth')} click(){this.tone(300,.04)}
  step(){this.tone(105,.035,'sine')}
  lane(direction){this.tone(direction<0?230:310,.07,'triangle')}
}

class ScoreManager {
  constructor(ui){ this.ui=ui; this.score=0; this.combo=0; this.elapsed=0; this.distance=0; this.lastSecond=0; }
  reset(){ this.score=0; this.combo=0; this.elapsed=0; this.distance=0; this.lastSecond=0; this.ui.updateScore(this); }
  update(delta,speed){ this.elapsed+=delta; this.distance+=speed*delta; const second=Math.floor(this.elapsed); if(second>this.lastSecond){ const passed=second-this.lastSecond; this.score-=passed; this.lastSecond=second; this.combo=Math.min(999,this.combo+passed); this.ui.updateScore(this); } }
  worsen(amount=1){ this.score=Math.min(-1,this.score-amount); this.ui.updateScore(this); }
  message(){ const abs=Math.abs(this.score); if(abs===0)return "Welcome! You haven't lost anything yet."; if(abs<25)return "You're doing terribly!"; if(abs<50)return "Impressive failure."; if(abs<100)return "Professional loser detected."; if(abs<250)return "You're actually very good at being bad."; if(abs<500)return "This is getting unnecessarily negative."; if(abs<1000)return "Legendary failure unlocked."; if(abs<5000)return "WHY ARE YOU STILL RUNNING?"; if(abs<10000)return "You have achieved absolutely nothing."; return "Congratulations. You are number one at losing points."; }
}

class UIManager {
  constructor(){ this.scoreEl=document.getElementById('score'); this.messageEl=document.getElementById('message'); this.menu=document.getElementById('menu'); this.gameOver=document.getElementById('gameOver'); this.howPanel=document.getElementById('howPanel'); }
  updateScore(scores){ this.scoreEl.textContent=scores.score; document.getElementById('distance').textContent=`${Math.floor(scores.distance)} m`; }
  updateSpeed(speed){ document.getElementById('speed').textContent=`${Math.floor(speed)} m/s`; }
  notify(text){ this.messageEl.textContent=text; this.messageEl.classList.add('show'); clearTimeout(this.messageTimer); this.messageTimer=setTimeout(()=>this.messageEl.classList.remove('show'),2300); }
  showMenu(){ this.menu.classList.add('active'); this.gameOver.classList.remove('active'); }
  hideMenu(){ this.menu.classList.remove('active'); }
  showHow(){ this.howPanel.classList.add('active'); }
  closeModals(){ this.howPanel.classList.remove('active'); }
  showContinuePrompt(){ document.getElementById('continuePanel').classList.add('active'); }
  hideContinuePrompt(){ document.getElementById('continuePanel').classList.remove('active'); }
  showGameOver(scores){ document.getElementById('finalScore').textContent=scores.score; document.getElementById('finalDistance').textContent=`${Math.floor(scores.distance)} m`; const mins=String(Math.floor(scores.elapsed/60)).padStart(2,'0'); const secs=String(Math.floor(scores.elapsed%60)).padStart(2,'0'); document.getElementById('finalTime').textContent=`${mins}:${secs}`; document.getElementById('finalMessage').innerHTML=`${scores.message().toUpperCase()}<br>YOU FAILED SUCCESSFULLY.`; this.gameOver.classList.add('active'); }
}

class Player {
  constructor(scene){ this.group=new THREE.Group(); this.scene=scene; this.lane=1; this.targetLane=1; this.y=0; this.verticalVelocity=0; this.sliding=false; this.dead=false; this.parts=[]; this.build(); scene.add(this.group); }
  build(){ const skin=new THREE.MeshStandardMaterial({color:0xc8f560,roughness:.5}); const dark=new THREE.MeshStandardMaterial({color:0x12151d,roughness:.7}); const orange=new THREE.MeshStandardMaterial({color:0xff6b35,emissive:0x2b0b02}); const cube=(x,y,z,sx,sy,sz,mat)=>{ const mesh=new THREE.Mesh(new THREE.BoxGeometry(sx,sy,sz),mat); mesh.position.set(x,y,z); mesh.castShadow=true; this.group.add(mesh); return mesh; }; this.body=cube(0,1.35,0,.52,.75,.36,dark); this.head=cube(0,1.95,0,.42,.42,.42,skin); this.armL=cube(-.4,1.35,0,.16,.62,.16,orange); this.armR=cube(.4,1.35,0,.16,.62,.16,orange); this.legL=cube(-.18,.64,0,.18,.72,.18,skin); this.legR=cube(.18,.64,0,.18,.72,.18,skin); this.parts=[this.armL,this.armR,this.legL,this.legR]; }
  update(delta,time){ const laneX=(this.targetLane-1)*2.25; this.group.position.x=THREE.MathUtils.damp(this.group.position.x,laneX,12,delta); if(this.dead){this.group.position.y-=delta*2.5;this.group.rotation.z+=delta*8;return;} if(this.y>0||this.verticalVelocity>0){ this.verticalVelocity-=19*delta; this.y+=this.verticalVelocity*delta; if(this.y<=0){this.y=0;this.verticalVelocity=0;} } this.group.position.y=this.y; const running=Math.sin(time*14); if(!this.sliding){ this.armL.rotation.x=running*.65; this.armR.rotation.x=-running*.65; this.legL.rotation.x=-running*.7; this.legR.rotation.x=running*.7; } this.group.scale.y=THREE.MathUtils.damp(this.group.scale.y,this.sliding?.58:1,15,delta); }
  laneMove(direction){ const previousLane=this.targetLane; this.targetLane=Math.max(0,Math.min(2,this.targetLane+direction)); const changed=this.targetLane!==previousLane; if(changed&&this.onLaneMove)this.onLaneMove(direction); return changed; }
  jump(){ if(this.y===0&&!this.sliding){this.verticalVelocity=8.2; return true} return false; }
  slide(){ if(this.y===0){this.sliding=true; clearTimeout(this.slideTimer); this.slideTimer=setTimeout(()=>this.sliding=false,650); return true} return false; }
  eliminate(){this.dead=true;this.verticalVelocity=4.5;}
  reset(){this.targetLane=1;this.group.position.set(0,0,0);this.group.rotation.set(0,0,0);this.group.scale.set(1,1,1);this.group.visible=true;this.y=0;this.verticalVelocity=0;this.sliding=false;this.dead=false;}
}

class ObstacleManager {
  constructor(scene){ this.scene=scene; this.items=[]; this.pool=[]; this.nextSpawn=4; this.materials=[new THREE.MeshStandardMaterial({color:0xff3d4c,emissive:0x3b0509}),new THREE.MeshStandardMaterial({color:0xffa72c}),new THREE.MeshStandardMaterial({color:0x8867ff})]; for(let i=0;i<24;i++)this.create(); }
  create(){ const group=new THREE.Group(); const mesh=new THREE.Mesh(new THREE.BoxGeometry(1.35,1.2,1.35),this.materials[this.pool.length%3]); mesh.position.y=.6; mesh.castShadow=true; group.add(mesh); const stripe=new THREE.Mesh(new THREE.BoxGeometry(1.48,.12,1.48),new THREE.MeshStandardMaterial({color:0x151923})); stripe.position.y=1.05; group.add(stripe); group.visible=false; this.scene.add(group); this.pool.push({group,kind:'box',spin:false}); }
  spawn(z,lane,kind){ const item=this.pool.find(obstacle=>!obstacle.group.visible); if(!item)return; item.group.visible=true; item.group.position.set((lane-1)*2.25,0,z); item.kind=kind||'box'; item.spin=item.kind==='box'&&Math.random()>.7; item.group.scale.set(1,item.kind==='barrier'?.55:1,1); this.items.push(item); }
  spawnWave(z){ const lanes=[0,1,2].sort(()=>Math.random()-.5); const pattern=Math.random(); if(pattern<.45){this.spawn(z,lanes[0],Math.random()>.7?'barrier':'box');}else if(pattern<.82){this.spawn(z,lanes[0],'box');this.spawn(z,lanes[1],Math.random()>.65?'barrier':'box');}else{this.spawn(z,lanes[0],'box');this.spawn(z-10,lanes[1],'barrier');this.spawn(z-20,lanes[2],'box');} }
  update(delta,player,speed){ this.nextSpawn-=delta; if(this.nextSpawn<=0){this.spawnWave(-82);this.nextSpawn=Math.max(3.4,5.8-speed*.08)+Math.random()*1.4;} for(let i=this.items.length-1;i>=0;i--){const item=this.items[i]; item.group.position.z+=speed*delta; if(item.spin)item.group.rotation.y+=delta*4; if(!player.dead){const dx=Math.abs(item.group.position.x-player.group.position.x), dz=Math.abs(item.group.position.z); const obstacleTop=item.kind==='barrier'?.7:1.2; const clearsObstacle=player.y>=obstacleTop-.12; const slidesUnder=player.sliding&&item.kind==='barrier'; if(dx<.82&&dz<1.05&&!clearsObstacle&&!slidesUnder){ item.group.visible=false; this.items.splice(i,1); return true; }} if(item.group.position.z>15){ item.group.visible=false; this.items.splice(i,1); } } return false; }
  reset(){this.items.forEach(item=>item.group.visible=false);this.items=[];this.nextSpawn=4;}
}

class EnvironmentManager {
  constructor(scene){ this.scene=scene; this.segments=[]; this.props=[]; this.animTime=0; this.buildRoad(); this.buildProps(); }
  material(color,rough=.8){return new THREE.MeshStandardMaterial({color,roughness:rough})}
  buildRoad(){ const roadMat=this.material(0x252932); const grassMat=this.material(0x15231f); for(let i=0;i<7;i++){const segment=new THREE.Group(); const road=new THREE.Mesh(new THREE.BoxGeometry(8,.2,30),roadMat);road.receiveShadow=true;segment.add(road);const left=new THREE.Mesh(new THREE.BoxGeometry(12,.12,30),grassMat);left.position.x=-10;segment.add(left);const right=left.clone();right.position.x=10;segment.add(right);for(const x of [-1.33,1.33]){const dash=new THREE.Mesh(new THREE.BoxGeometry(.12,.03,2.4),this.material(0xded7b5));for(let j=0;j<4;j++){const line=dash.clone();line.position.set(x,.13,-13+j*8);segment.add(line)}}segment.position.z=-i*30;this.scene.add(segment);this.segments.push(segment);} }
  buildProps(){ for(let i=0;i<28;i++){const side=i%2?-1:1;const group=new THREE.Group();const h=3+Math.random()*6;const building=new THREE.Mesh(new THREE.BoxGeometry(2+Math.random()*2,h,2),this.material(i%3?0x202a35:0x303b46));building.position.y=h/2;group.add(building);for(let w=0;w<3;w++){const light=new THREE.Mesh(new THREE.BoxGeometry(.13,.2,.03),this.material(0xc8f560));light.position.set(-.5+(w%2)*.8,1+w*1.2,1.02);group.add(light)}group.position.set(side*(7+Math.random()*5),0,-10-Math.random()*170);this.scene.add(group);this.props.push(group);} for(let i=0;i<18;i++){const side=i%2?-1:1;const tree=new THREE.Group();const trunk=new THREE.Mesh(new THREE.CylinderGeometry(.12,.2,2.1,7),this.material(0x5b3b2c));trunk.position.y=1.05;trunk.castShadow=true;tree.add(trunk);const crown=new THREE.Mesh(new THREE.ConeGeometry(.9+Math.random()*.35,2.4+Math.random()*.6,8),this.material(i%3?0x2f7d4b:0x4f9a52));crown.position.y=2.7;crown.castShadow=true;tree.add(crown);tree.userData.isTree=true;tree.userData.sway=Math.random()*Math.PI*2;tree.position.set(side*(5.8+Math.random()*2.8),0,-15-Math.random()*180);this.scene.add(tree);this.props.push(tree);} for(let i=0;i<10;i++){const cloud=new THREE.Mesh(new THREE.SphereGeometry(2+Math.random()*2,8,6),this.material(0x38414b));cloud.scale.set(2.5,.45,1);cloud.position.set(-25+Math.random()*50,12+Math.random()*5,-20-i*30);this.scene.add(cloud);this.props.push(cloud);} }
  update(delta,speed){ this.animTime+=delta; for(const segment of this.segments){segment.position.z+=speed*delta;if(segment.position.z>30)segment.position.z-=210;} for(const prop of this.props){prop.position.z+=speed*delta;if(prop.userData.isTree){prop.rotation.z=Math.sin(this.animTime*2.2+prop.userData.sway)*.045;prop.children[1].rotation.y=Math.sin(this.animTime*1.7+prop.userData.sway)*.08;}if(prop.position.z>20)prop.position.z-=210;} }
}

class LeaderboardManager { save(score){const board=JSON.parse(localStorage.getItem('negativeRunnerBoard')||'[]');board.push({name:'You',score});board.sort((a,b)=>a.score-b.score);localStorage.setItem('negativeRunnerBoard',JSON.stringify(board.slice(0,5)));} }

class Game {
  constructor(){ this.ui=new UIManager();this.audio=new AudioManager();this.score=new ScoreManager(this.ui);this.leaderboard=new LeaderboardManager();this.running=false;this.paused=false;this.time=0;this.speed=12;this.hitCooldown=0;this.stepTimer=0;this.milestones=new Set();this.continuePromptShown=false;this.setupThree();this.player.onLaneMove=direction=>this.audio.lane(direction);this.bind();this.animate=this.animate.bind(this);requestAnimationFrame(this.animate); }
  setupThree(){ this.scene=new THREE.Scene();this.scene.background=new THREE.Color(0x080d15);this.scene.fog=new THREE.Fog(0x080d15,25,155);this.camera=new THREE.PerspectiveCamera(55,innerWidth/innerHeight,.1,300);this.camera.position.set(0,4.8,9);this.camera.lookAt(0,1,-25);this.renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});this.renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));this.renderer.setSize(innerWidth,innerHeight);this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=THREE.PCFSoftShadowMap;document.getElementById('scene').appendChild(this.renderer.domElement);const hemi=new THREE.HemisphereLight(0x9aaacc,0x151a13,1.4);this.scene.add(hemi);const sun=new THREE.DirectionalLight(0xd9e8ff,2.2);sun.position.set(-8,16,10);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);this.scene.add(sun);this.environment=new EnvironmentManager(this.scene);this.obstacles=new ObstacleManager(this.scene);this.player=new Player(this.scene);this.stars=new THREE.Points(new THREE.BufferGeometry(),new THREE.PointsMaterial({color:0xc8f560,size:.08}));const positions=[];for(let i=0;i<180;i++)positions.push((Math.random()-.5)*100,10+Math.random()*35,-Math.random()*190);this.stars.geometry.setAttribute('position',new THREE.Float32BufferAttribute(positions,3));this.scene.add(this.stars);addEventListener('resize',()=>{this.camera.aspect=innerWidth/innerHeight;this.camera.updateProjectionMatrix();this.renderer.setSize(innerWidth,innerHeight)}); }
  bind(){ const move=e=>{if(e.repeat)return;const key=e.key.toLowerCase();if(key==='a'||key==='arrowleft')this.player.laneMove(-1);if(key==='d'||key==='arrowright')this.player.laneMove(1);if(key===' '||key==='arrowup'){if(this.player.jump())this.audio.jump();}if(key==='s'||key==='arrowdown')this.player.slide();if(key==='p')this.togglePause();if(key==='r'&&!this.running)this.start();};addEventListener('keydown',move);document.getElementById('startButton').onclick=()=>this.start();document.getElementById('respawnButton').onclick=()=>this.start();document.getElementById('startRunButton').onclick=()=>this.start();document.getElementById('menuButton').onclick=()=>{this.running=false;this.ui.showMenu()};document.getElementById('hudMenuButton').onclick=()=>{this.running=false;this.paused=false;this.ui.hideContinuePrompt();this.ui.showMenu();this.ui.notify('RETURNED TO MAIN MENU.');};document.getElementById('pauseButton').onclick=()=>this.togglePause();document.getElementById('muteButton').onclick=()=>{this.audio.muted=!this.audio.muted;document.getElementById('muteButton').textContent=this.audio.muted?'⊘':'◖))'};document.getElementById('howButton').onclick=()=>this.ui.showHow();document.querySelectorAll('[data-close]').forEach(button=>button.onclick=()=>this.ui.closeModals());document.getElementById('settingsButton').onclick=()=>this.ui.notify('SETTINGS: YOU ARE ALREADY RUNNING THE DEFAULT SETTING.');document.getElementById('creditsButton').onclick=()=>this.ui.notify('MADE BY THE FAILURE SYSTEMS DEPARTMENT.');document.getElementById('worseButton').onclick=()=>{if(this.running){this.score.worsen();this.checkMilestones();this.audio.point();if(this.score.score>-50||this.score.score<-100||!this.milestones.has(-50)&&!this.milestones.has(-100))this.ui.notify('Thank you for making things worse.')}else this.ui.notify('Start running before you ruin the score.')};document.getElementById('panicButton').onclick=()=>this.ui.notify('PANIC MODE ACTIVATED // ...nothing changed.');document.getElementById('continueButton').onclick=()=>{this.ui.hideContinuePrompt();this.ui.notify('HaHaHa u losed. CONTINUE RUNNING.');};document.getElementById('endAtHundredButton').onclick=()=>{this.ui.hideContinuePrompt();this.end();};document.querySelectorAll('[data-control]').forEach(button=>button.addEventListener('pointerdown',()=>{const control=button.dataset.control;if(control==='left')this.player.laneMove(-1);if(control==='right')this.player.laneMove(1);if(control==='jump'&&this.player.jump())this.audio.jump();if(control==='slide')this.player.slide()})); }
  start(){this.audio.init();this.running=true;this.paused=false;this.time=0;this.speed=12;this.hitCooldown=0;this.stepTimer=0;this.milestones.clear();this.continuePromptShown=false;this.score.reset();this.player.reset();this.obstacles.reset();this.ui.hideMenu();this.ui.hideContinuePrompt();this.ui.gameOver.classList.remove('active');this.ui.notify('SURVIVE TO LOSE MORE.');}
  togglePause(){if(!this.running)return;this.paused=!this.paused;this.ui.notify(this.paused?'PAUSED. YOUR SCORE IS NOT GETTING BETTER.':'RESUMED. KEEP FAILING.');}
  end(){this.running=false;this.audio.gameOver();this.leaderboard.save(this.score.score);this.ui.showGameOver(this.score);}
  checkMilestones(){if(this.score.score<=-50&&!this.milestones.has(-50)){this.milestones.add(-50);this.ui.notify('YOU REACHED -50. NOW REACH -100 FOR A SURPRISE.');}if(this.score.score<=-100&&!this.milestones.has(-100)){this.milestones.add(-100);if(!this.continuePromptShown){this.continuePromptShown=true;this.ui.showContinuePrompt();}}}
  animate(now){requestAnimationFrame(this.animate);const delta=Math.min(.05,(now-(this.lastTime||now))/1000);this.lastTime=now;this.time+=delta;if(this.running&&!this.paused){this.speed=Math.min(28,12+this.score.elapsed*.045);this.score.update(delta,this.speed);this.checkMilestones();this.ui.updateSpeed(this.speed);this.environment.update(delta,this.speed);this.player.update(delta,this.time);this.stepTimer-=delta;if(this.stepTimer<=0&&!this.player.dead){this.audio.step();this.stepTimer=Math.max(.22,.38-(this.speed-12)*.008);}this.hitCooldown-=delta;const hit=this.obstacles.update(delta,this.player,this.speed);if(hit&&this.hitCooldown<=0){this.hitCooldown=1.2;this.score.worsen(10);this.score.combo=0;this.player.eliminate();this.audio.collision();this.ui.notify(`ELIMINATED BY OBSTACLE. ${this.score.message()}`);this.camera.position.x+=.3;setTimeout(()=>this.camera.position.x=0,120);setTimeout(()=>this.end(),650);}this.camera.position.y=4.8+Math.sin(this.time*7)*.025;this.camera.lookAt(this.player.group.position.x*.18,1.2,-25);this.stars.rotation.y+=delta*.01;}this.renderer.render(this.scene,this.camera);}
}
window.addEventListener('load',()=>{
  const game=new Game();
  const fitToSixteenNine=()=>{
    const ratio=16/9;
    const shell=document.getElementById('game-shell');
    let width=shell.clientWidth;
    let height=shell.clientHeight;
    if(width/height>ratio) width=Math.floor(height*ratio);
    else height=Math.floor(width/ratio);
    game.renderer.setSize(width,height,false);
    game.renderer.domElement.style.width=`${width}px`;
    game.renderer.domElement.style.height=`${height}px`;
    game.renderer.domElement.style.margin='auto';
    document.getElementById('scene').style.display='grid';
    document.getElementById('scene').style.placeItems='center';
    game.camera.aspect=ratio;
    game.camera.updateProjectionMatrix();
  };
  fitToSixteenNine();
  addEventListener('resize',fitToSixteenNine);
});